name: flutter_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_web_auth: ^0.6.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  dio: ^5.3.3
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/google_logo.png

  uses-material-design: true



